import sys
import os
import json
import socket
import threading
import sqlite3
import pandas as pd
from datetime import datetime

# Setup paths
VIPER = r"C:\Viper"
PROJ_DB = os.path.join(VIPER, "databases", "projects", "projects.db")
CODE_DB = os.path.join(VIPER, "databases", "code", "code.db")

# NMCT DB Manager Path
sys.path.append(r"C:\Users\viper\gan-otg-db")
try:
    import nmct_db_manager
except ImportError:
    nmct_db_manager = None

# Default OTG Host configurations (Ethernet over USB / RNDIS)
DEFAULT_HOST = "0.0.0.0" # Listen on all interfaces
DEFAULT_PORT = 8080

def get_database_status():
    """Queries current stats of active databases."""
    status_list = []
    try:
        conn = sqlite3.connect(PROJ_DB)
        cursor = conn.cursor()
        cursor.execute("SELECT id, name, language, status, local_path FROM projects WHERE status='active'")
        rows = cursor.fetchall()
        for r in rows:
            status_list.append({
                "id": r[0],
                "name": r[1],
                "language": r[2],
                "status": r[3],
                "local_path": r[4]
            })
        conn.close()
    except Exception as e:
        status_list = [{"error": str(e)}]
    return status_list

def handle_gan_batch(batch_data):
    """
    Receives synthetic training sample batch from Generator or Discriminator.
    Logs telemetry costs and stores code snippets to the 'Never Make Code Twice' DB if quality threshold is met.
    """
    # Ex: batch_data = {"name": "gen_schema", "lang": "sql", "code": "...", "fitness": 0.85, "cost": 0.005}
    name = batch_data.get("name", "synthetic_snippet")
    lang = batch_data.get("lang", "sql")
    code = batch_data.get("code", "")
    fitness = batch_data.get("fitness", 0.80)
    desc = batch_data.get("description", "Synthetic code generated by OTG GAN")
    cost = batch_data.get("cost", 0.001)

    if nmct_db_manager and fitness >= 0.85:
        # Save to Never Make Code Twice Database
        nmct_db_manager.store_snippet(
            name=name,
            language=lang,
            performative="achieve",
            description=desc,
            code=code,
            fitness_score=fitness
        )
        print(f"[GAN-OTG] Saved high-quality synthetic snippet: {name} (fitness={fitness})")
        return {"status": "stored", "detail": "Snippet added to NMCT catalog"}
    return {"status": "received", "detail": "Batch received, did not meet NMCT fitness threshold"}

def handle_client(client_socket, client_address):
    """Handles incoming client connection over OTG."""
    print(f"[OTG-Bridge] Connection established with Computer A: {client_address}")
    client_socket.settimeout(30.0)
    
    buffer = ""
    try:
        while True:
            data = client_socket.recv(4096).decode('utf-8')
            if not data:
                break
                
            buffer += data
            while "\n" in buffer:
                line, buffer = buffer.split("\n", 1)
                line = line.strip()
                if not line:
                    continue
                    
                try:
                    request = json.loads(line)
                    action = request.get("action", "ping")
                    print(f"[OTG-Bridge] Received action: {action}")
                    
                    response = {"status": "ok", "timestamp": datetime.utcnow().isoformat()}
                    
                    if action == "ping":
                        response["data"] = "pong"
                    elif action == "db_status":
                        response["data"] = get_database_status()
                    elif action == "gan_batch":
                        batch = request.get("batch", {})
                        response["data"] = handle_gan_batch(batch)
                    elif action == "lookup_nmct":
                        lang = request.get("language", "python")
                        perf = request.get("performative", "ask")
                        q = request.get("query", None)
                        if nmct_db_manager:
                            res = nmct_db_manager.lookup_snippet(lang, perf, q)
                            response["data"] = res if res else "Not found"
                        else:
                            response["data"] = "NMCT module unavailable"
                    else:
                        response["status"] = "error"
                        response["message"] = f"Unknown action: {action}"
                        
                    client_socket.sendall((json.dumps(response) + "\n").encode('utf-8'))
                    
                except json.JSONDecodeError:
                    err_res = {"status": "error", "message": "Invalid JSON payload"}
                    client_socket.sendall((json.dumps(err_res) + "\n").encode('utf-8'))
    except socket.timeout:
        print(f"[OTG-Bridge] Connection timed out with client {client_address}")
    except Exception as e:
        print(f"[OTG-Bridge] Error handling client: {e}")
    finally:
        client_socket.close()
        print(f"[OTG-Bridge] Closed connection with client {client_address}")

def start_server(host=DEFAULT_HOST, port=DEFAULT_PORT):
    """Starts the TCP server loop on the USB OTG network interface."""
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        server.bind((host, port))
        server.listen(5)
        print(f"[OTG-Bridge] Listening for Computer A at {host}:{port}...")
    except OSError as oe:
        print(f"[OTG-Bridge] Port {port} busy. Retrying fallback port {port + 5}...")
        try:
            server.bind((host, port + 5))
            server.listen(5)
            print(f"[OTG-Bridge] Listening for Computer A on fallback port {port + 5}...")
        except OSError:
            print("[OTG-Bridge] Socket binding failed. Running in Drive K: file-only mode.")
            # Keep thread alive to allow Drive K watcher to run
            import time
            while True:
                time.sleep(3600)
            return

    try:
        while True:
            client_sock, client_addr = server.accept()
            t = threading.Thread(target=handle_client, args=(client_sock, client_addr), daemon=True)
            t.start()
    except KeyboardInterrupt:
        print("\n[OTG-Bridge] Server stopped by user.")
    except Exception as e:
        print(f"[OTG-Bridge] Server error: {e}")
    finally:
        server.close()

def drive_k_communication_loop(drive_path="K:\\"):
    """
    Watches drive K: (Machine 2 virtual link) for commands in K:\inbound\*.json
    Processes them, and writes results to K:\outbound\res_*.json
    Updates K:\m2_heartbeat.json.
    """
    import time
    inbound_dir = os.path.join(drive_path, "inbound")
    outbound_dir = os.path.join(drive_path, "outbound")
    heartbeat_path = os.path.join(drive_path, "m2_heartbeat.json")
    
    print(f"[OTG-Bridge-K] Starting drive K: loop at {drive_path}")
    
    # Initialize directory structure if drive is writable
    try:
        os.makedirs(inbound_dir, exist_ok=True)
        os.makedirs(outbound_dir, exist_ok=True)
    except Exception as e:
        print(f"[OTG-Bridge-K] Warning: could not initialize directories on {drive_path}: {e}")
        
    last_heartbeat = 0
    while True:
        try:
            # 1. Update heartbeat every 10 seconds
            now = time.time()
            if now - last_heartbeat > 10:
                if os.path.exists(drive_path):
                    os.makedirs(inbound_dir, exist_ok=True)
                    os.makedirs(outbound_dir, exist_ok=True)
                    with open(heartbeat_path, "w") as f:
                        json.dump({"status": "active", "timestamp": datetime.utcnow().isoformat()}, f)
                    last_heartbeat = now
            
            # 2. Check inbound command files
            if os.path.exists(inbound_dir):
                for filename in os.listdir(inbound_dir):
                    if filename.endswith(".json") and not filename.endswith(".tmp"):
                        filepath = os.path.join(inbound_dir, filename)
                        time.sleep(0.1) # Wait slightly for write to finish
                        try:
                            with open(filepath, "r") as f:
                                request = json.load(f)
                            
                            # Remove the processed request file immediately to avoid double execution
                            os.remove(filepath)
                            
                            action = request.get("action", "ping")
                            print(f"[OTG-Bridge-K] Received action from K: {action}")
                            
                            response_data = {"status": "ok", "timestamp": datetime.utcnow().isoformat()}
                            
                            if action == "ping":
                                response_data["data"] = "pong"
                            elif action == "db_status":
                                response_data["data"] = get_database_status()
                            elif action == "gan_batch":
                                batch = request.get("batch", {})
                                response_data["data"] = handle_gan_batch(batch)
                            elif action == "lookup_nmct":
                                lang = request.get("language", "python")
                                perf = request.get("performative", "ask")
                                q = request.get("query", None)
                                if nmct_db_manager:
                                    res = nmct_db_manager.lookup_snippet(lang, perf, q)
                                    response_data["data"] = res if res else "Not found"
                                else:
                                    response_data["data"] = "NMCT module unavailable"
                            else:
                                response_data["status"] = "error"
                                response_data["message"] = f"Unknown action: {action}"
                            
                            # Write response to outbound directory
                            res_filename = f"res_{filename}"
                            res_filepath = os.path.join(outbound_dir, res_filename)
                            tmp_filepath = res_filepath + ".tmp"
                            
                            with open(tmp_filepath, "w") as f:
                                json.dump(response_data, f, indent=2)
                            os.replace(tmp_filepath, res_filepath)
                            print(f"[OTG-Bridge-K] Wrote response to K: {res_filepath}")
                            
                        except Exception as e:
                            print(f"[OTG-Bridge-K] Error processing file {filename}: {e}")
                            if os.path.exists(filepath):
                                try:
                                    os.remove(filepath)
                                except:
                                    pass
                                    
        except Exception as e:
            pass
            
        time.sleep(1.0)

if __name__ == "__main__":
    host = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_HOST
    port = int(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_PORT
    
    # Start the Drive K: communication loop in a background thread
    k_thread = threading.Thread(target=drive_k_communication_loop, args=("K:\\",), daemon=True)
    k_thread.start()
    
    start_server(host, port)
