import sys
import os
import json
import socket
import threading
import sqlite3
import pandas as pd
from datetime import datetime

# Setup paths
VIPER = r"C:\Viper"
PROJ_DB = os.path.join(VIPER, "databases", "projects", "projects.db")
CODE_DB = os.path.join(VIPER, "databases", "code", "code.db")

# NMCT DB Manager Path
sys.path.append(r"C:\Users\viper\gan-otg-db")
try:
    import nmct_db_manager
except ImportError:
    nmct_db_manager = None

# Default OTG Host configurations (Ethernet over USB / RNDIS)
DEFAULT_HOST = "0.0.0.0" # Listen on all interfaces
DEFAULT_PORT = 8080

def get_database_status():
    """Queries current stats of active databases."""
    status_list = []
    try:
        conn = sqlite3.connect(PROJ_DB)
        cursor = conn.cursor()
        cursor.execute("SELECT id, name, language, status, local_path FROM projects WHERE status='active'")
        rows = cursor.fetchall()
        for r in rows:
            status_list.append({
                "id": r[0],
                "name": r[1],
                "language": r[2],
                "status": r[3],
                "local_path": r[4]
            })
        conn.close()
    except Exception as e:
        status_list = [{"error": str(e)}]
    return status_list

def handle_gan_batch(batch_data):
    """
    Receives synthetic training sample batch from Generator or Discriminator.
    Logs telemetry costs and stores code snippets to the 'Never Make Code Twice' DB if quality threshold is met.
    """
    # Ex: batch_data = {"name": "gen_schema", "lang": "sql", "code": "...", "fitness": 0.85, "cost": 0.005}
    name = batch_data.get("name", "synthetic_snippet")
    lang = batch_data.get("lang", "sql")
    code = batch_data.get("code", "")
    fitness = batch_data.get("fitness", 0.80)
    desc = batch_data.get("description", "Synthetic code generated by OTG GAN")
    cost = batch_data.get("cost", 0.001)

    if nmct_db_manager and fitness >= 0.85:
        # Save to Never Make Code Twice Database
        nmct_db_manager.store_snippet(
            name=name,
            language=lang,
            performative="achieve",
            description=desc,
            code=code,
            fitness_score=fitness
        )
        print(f"[GAN-OTG] Saved high-quality synthetic snippet: {name} (fitness={fitness})")
        return {"status": "stored", "detail": "Snippet added to NMCT catalog"}
    return {"status": "received", "detail": "Batch received, did not meet NMCT fitness threshold"}

def handle_client(client_socket, client_address):
    """Handles incoming client connection over OTG."""
    print(f"[OTG-Bridge] Connection established with Computer A: {client_address}")
    client_socket.settimeout(30.0)
    
    buffer = ""
    try:
        while True:
            data = client_socket.recv(4096).decode('utf-8')
            if not data:
                break
                
            buffer += data
            while "\n" in buffer:
                line, buffer = buffer.split("\n", 1)
                line = line.strip()
                if not line:
                    continue
                    
                try:
                    request = json.loads(line)
                    action = request.get("action", "ping")
                    print(f"[OTG-Bridge] Received action: {action}")
                    
                    response = {"status": "ok", "timestamp": datetime.utcnow().isoformat()}
                    
                    if action == "ping":
                        response["data"] = "pong"
                    elif action == "db_status":
                        response["data"] = get_database_status()
                    elif action == "gan_batch":
                        batch = request.get("batch", {})
                        response["data"] = handle_gan_batch(batch)
                    elif action == "lookup_nmct":
                        lang = request.get("language", "python")
                        perf = request.get("performative", "ask")
                        q = request.get("query", None)
                        if nmct_db_manager:
                            res = nmct_db_manager.lookup_snippet(lang, perf, q)
                            response["data"] = res if res else "Not found"
                        else:
                            response["data"] = "NMCT module unavailable"
                    else:
                        response["status"] = "error"
                        response["message"] = f"Unknown action: {action}"
                        
                    client_socket.sendall((json.dumps(response) + "\n").encode('utf-8'))
                    
                except json.JSONDecodeError:
                    err_res = {"status": "error", "message": "Invalid JSON payload"}
                    client_socket.sendall((json.dumps(err_res) + "\n").encode('utf-8'))
    except socket.timeout:
        print(f"[OTG-Bridge] Connection timed out with client {client_address}")
    except Exception as e:
        print(f"[OTG-Bridge] Error handling client: {e}")
    finally:
        client_socket.close()
        print(f"[OTG-Bridge] Closed connection with client {client_address}")

def start_server(host=DEFAULT_HOST, port=DEFAULT_PORT):
    """Starts the TCP server loop on the USB OTG network interface."""
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        server.bind((host, port))
        server.listen(5)
        print(f"[OTG-Bridge] Listening for Computer A at {host}:{port}...")
        
        while True:
            client_sock, client_addr = server.accept()
            t = threading.Thread(target=handle_client, args=(client_sock, client_addr), daemon=True)
            t.start()
    except KeyboardInterrupt:
        print("\n[OTG-Bridge] Server stopped by user.")
    except Exception as e:
        print(f"[OTG-Bridge] Server error: {e}")
    finally:
        server.close()

if __name__ == "__main__":
    host = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_HOST
    port = int(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_PORT
    start_server(host, port)
