"""LOCAL PROSE — build the chat corpus from the fleet's own writing.

WHY
    chat_plateau() reads state/corpus/chat_corpus.jsonl. That file did not exist, so
    _gather_corpus_texts fell through to `journal.jsonl` -- 4.6 KB of the agent's own log
    lines, which read "mined is_even_py -> sealed 06b009fe" and "orchestrator_py: mine failed".

    An order-2 Markov chain over that corpus produces exactly what was observed:

        "lora to gguf py: lora to gguf py: utils py - sealed 40"
        plateau ✓ · 9 candidates · H=4.134

    Nothing was broken. The plateau really had converged, the entropy really was 4.134, and the
    text really is the most coherent continuation available -- of a distribution over FILENAMES.
    The mathematics was answering the question it was given. It was given the wrong corpus.

    webcrawl.py already solves this from the network. This module solves it from disk, which on
    this box is the much larger and much better source: the fleet's modules carry long
    explanatory docstrings and the repos carry hand-written READMEs. No network, no rate limit,
    no cooldown, and the prose is about the machine's own world, so a generated sentence has a
    chance of being about something the agent can act on.

WHAT COUNTS AS PROSE
    Module/class/function docstrings, and hand-written markdown. Extraction is by `ast`, not by
    regex: a regex over triple quotes also captures every string literal, and string literals in
    this codebase are SQL and format templates. Teaching the chain SQL would be the filename
    mistake a second time.

WHAT IS DELIBERATELY EXCLUDED
    CHANGELOG.md, ROADMAP.md and TASKS.md are written by Viper's auto-docs. They are template
    text repeated across 58 repos, so they would dominate the transition table by sheer count and
    the chain's most probable sentence would become "Auto-generated by Viper auto-docs @". A
    corpus is not improved by volume that says nothing.
"""
import ast
import hashlib
import os
import re

# Auto-generated docs: identical boilerplate in every repo, so its n-grams outvote real writing.
GENERATED = {"CHANGELOG.md", "ROADMAP.md", "TASKS.md", "INVENTORY.md"}
SKIP_DIRS = {".git", "__pycache__", "node_modules", ".venv", "venv", "target",
             ".pytest_cache", "build", "dist", ".mypy_cache", "backups"}
MIN_DOC = 120          # shorter than this is a label, not prose
MAX_DOC = 4000         # matches the per-text cap _gather_corpus_texts applies


# Lines that are documentation FURNITURE rather than writing: install steps, CLI flags,
# dependency pins, version tables. They are the majority of a README by volume and none of it is
# a sentence, so admitting them makes the chain fluent in "pip install --upgrade" and nothing else.
_FURNITURE = re.compile(
    r"(pip install|npm install|apt-get|winget|choco|docker run|git clone"
    r"|https?://|www\.|\bv?\d+\.\d+\.\d+"          # URLs, semver pins
    r"|^\s*[-*]\s*[`\-]|^\s*\d+\.\s|--[a-z][a-z-]{2,}"   # bullets, numbered steps, CLI flags
    r"|\.(exe|dll|whl|tar|gz|zip|json|yaml|yml|toml|cfg|ini)\b)",
    re.I | re.M)


def _is_prose(text):
    """Prose, not a code fragment, a table, or documentation furniture.

    The first version tested only "mostly letters, a few full stops", which the fleet's READMEs
    passed easily -- so the corpus learned "cuda 13: same as server but compiled with cuda 12
    support" and "linux arm 64". Those really are sentences by punctuation count; they are just
    not language anyone thinks in.

    Three structural tests, no keyword lists beyond the furniture pattern:
      1. enough real words, and words of believable average length;
      2. mostly letters, so ASCII diagrams and arg tables are out;
      3. furniture density under a threshold -- a paragraph MENTIONING a flag is fine, a block
         that is nothing but flags is not.
    """
    if len(text) < MIN_DOC:
        return False
    letters = sum(ch.isalpha() or ch.isspace() for ch in text)
    if letters / len(text) < 0.80:          # mostly symbols => diagram or table
        return False
    words = text.split()
    if len(words) < 25:
        return False
    alpha_words = [w for w in words if w.isalpha()]
    if len(alpha_words) / len(words) < 0.70:          # identifiers/versions outnumber words
        return False
    avg = sum(len(w) for w in alpha_words) / len(alpha_words)
    if not 3.0 <= avg <= 9.0:               # outside this is tokens, not English
        return False
    if len(_FURNITURE.findall(text)) > len(words) / 40:
        return False
    return text.count(".") + text.count("?") + text.count("!") >= 2


def _clean(text):
    """Collapse whitespace and drop the box-drawing rules used as section dividers."""
    text = re.sub(r"[─━═╌·-]{4,}", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def docstrings(py_path):
    """Every docstring in one module, via ast.

    ast.get_docstring is used rather than a triple-quote regex because a regex cannot tell a
    docstring from a SQL literal, and this codebase is full of the latter.
    """
    out = []
    try:
        with open(py_path, "r", encoding="utf-8", errors="replace") as f:
            tree = ast.parse(f.read())
    except (OSError, SyntaxError, ValueError):
        return out
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            try:
                d = ast.get_docstring(node)
            except Exception:
                continue
            if d:
                out.append(_clean(d)[:MAX_DOC])
    return out


def markdown(md_path):
    """Hand-written markdown, stripped of fences and headers."""
    try:
        with open(md_path, "r", encoding="utf-8", errors="replace") as f:
            text = f.read()
    except OSError:
        return []
    text = re.sub(r"```.*?```", " ", text, flags=re.S)      # code blocks are not prose
    text = re.sub(r"^\s{0,3}#{1,6}\s*", "", text, flags=re.M)
    text = re.sub(r"!?\[([^\]]*)\]\([^)]*\)", r"\1", text)  # keep link text, drop URLs
    text = re.sub(r"^\s*\|.*\|\s*$", " ", text, flags=re.M)  # tables
    return [_clean(text)[:MAX_DOC]]


def harvest(roots, limit_files=4000, skip_files=0):
    """Walk `roots` and yield (source, text) for everything that reads as prose.

    `skip_files` skips that many candidate files before collecting, so a caller can rotate a
    window through the fleet across successive passes instead of re-reading the same head of the
    walk every time. The walk order is sorted, which is what makes a saved offset mean the same
    thing on the next run.
    """
    seen = set()
    for root in roots:
        if not os.path.isdir(root):
            continue
        n = 0
        skipped = 0
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = sorted(d for d in dirnames
                                 if d not in SKIP_DIRS and not d.startswith("."))
            for fn in sorted(filenames):
                if n >= limit_files:
                    break
                if skipped < skip_files and (fn.endswith(".py") or fn.endswith(".md")):
                    skipped += 1
                    continue
                path = os.path.join(dirpath, fn)
                if fn.endswith(".py"):
                    chunks = docstrings(path)
                elif fn.endswith(".md") and fn not in GENERATED:
                    chunks = markdown(path)
                else:
                    continue
                n += 1
                for chunk in chunks:
                    if not _is_prose(chunk):
                        continue
                    # Dedup on content, not path: the same docstring is vendored into several
                    # repos, and duplicates would skew the transition table toward whatever
                    # happens to have been copied most.
                    h = hashlib.sha1(chunk.encode("utf-8")).hexdigest()
                    if h in seen:
                        continue
                    seen.add(h)
                    yield os.path.relpath(path, root), chunk


def populate(trainer, roots, limit_files=4000):
    """Feed harvested prose into the chat corpus through CrawlTrainer's own door.

    Goes via append_corpus rather than writing the JSONL directly, so there is exactly one
    writer of the corpus format and one place that decides what a corpus record looks like.
    """
    docs = chars = 0
    for source, text in harvest(roots, limit_files=limit_files):
        got = trainer.append_corpus("local:" + source.replace("\\", "/"), text)
        if got:
            docs += 1
            chars += got
    return {"docs": docs, "chars": chars, "corpus": trainer.corpus_stats()}

# LOCATIONS - this file lives in more than one place
#
#   live:  C:\Viper\projects\BDI_FSM_AGENT
#          -> C:\Users\viper\gan-otg-db\BDI_FSM_AGENT
#   mirror: J:\ViperVault\code\projects\BDI_FSM_AGENT
#   mirror: C:\Users\viper\gan-otg-db\BDI_FSM_AGENT
#
#   live detail (freshness, git coverage): docs\LOCATIONS.md
#   regenerate: python location_stamp.py apply
# end LOCATIONS
